# Generated by Django 5.1.1 on 2024-09-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkagenda', '0004_post_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
