# Generated by Django 5.1.1 on 2024-10-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkagenda', '0006_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['datum']},
        ),
    ]
