# Generated by Django 5.1.1 on 2024-10-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkagenda', '0007_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Dagelijks'), ('weekly', 'Wekelijks'), ('monthly', 'Maandelijks')], max_length=20, null=True),
        ),
    ]
