# Generated by Django 5.1.1 on 2024-10-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkagenda', '0008_alter_post_options_post_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='freq_einddatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
