# Generated by Django 5.1.1 on 2024-11-07 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkagenda', '0014_myimagemodel_remove_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
