# Generated by Django 5.1.1 on 2024-11-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkagenda', '0015_prog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImageModel',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
