# Generated by Django 5.1.1 on 2024-11-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkagenda', '0016_delete_myimagemodel_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prog',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='prog',
            old_name='start_time',
            new_name='start',
        ),
        migrations.AddField(
            model_name='prog',
            name='herhaling_einde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prog',
            name='herhaling_interval',
            field=models.CharField(blank=True, choices=[('wekelijks', 'Wekelijks'), ('wekelijks2', 'Wekelijks2'), ('maandelijks', 'Maandelijks')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prog',
            name='is_herhaling',
            field=models.BooleanField(default=False),
        ),
    ]
