# Generated by Django 3.2.25 on 2024-03-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkagenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='datum',
        ),
    ]
